# Generated by Django 4.2.7 on 2024-01-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraRAGP',
            fields=[
                ('idCarreraRAGP', models.AutoField(primary_key=True, serialize=False)),
                ('estudianteRAGP', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('nombreCarreraRAGP', models.CharField(max_length=100)),
                ('directorCarreraRAGP', models.CharField(max_length=100)),
                ('logoCarreraRAGP', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CursoRAGP',
            fields=[
                ('idCursoRAGP', models.AutoField(primary_key=True, serialize=False)),
                ('nivelCursoRAGP', models.CharField(max_length=50)),
                ('descripcionCursoRAGP', models.TextField()),
                ('aulaCursoRAGP', models.CharField(max_length=20)),
                ('numeroEstudiantesRAGP', models.IntegerField()),
                ('estudianteRAGP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.carreraragp')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaRAGP',
            fields=[
                ('idAsignaturaRAGP', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAsignaturaRAGP', models.CharField(max_length=100)),
                ('creditosAsignaturaRAGP', models.PositiveIntegerField()),
                ('fechaInicioAsignaturaRAGP', models.DateField()),
                ('fechaFinalizacionAsignaturaRAGP', models.DateField()),
                ('profesorAsignaturaRAGP', models.CharField(max_length=100)),
                ('silaboAsignaturaRAGP', models.FileField(blank=True, null=True, upload_to='silabos/')),
                ('mandilAsignaturaRAGP', models.CharField(blank=True, max_length=100, null=True)),
                ('estudianteRAGP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.carreraragp')),
            ],
        ),
    ]
