# Generated by Django 4.2.7 on 2024-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreraragp',
            name='logoCarreraRAGP',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
